PROJECT_NAME = "DataQuality"
API_VERSION = "/api/v1"

# Lifetime of HTTP Cookie
# Default: 8 hrs
AUTH_LIFETIME_IN_SECONDS = "28800"

# SECRET_KEY, OAUTH_CLIENT_ID, OAUTH_SECRET, ADMIN_PASSWORD should be stored in a Secret Store
# like AWS Parameter Store or AWS Secrets Manager
SECRET_KEY = "jSE9Q7_5g1MDpCz7wU1xmcmz27RhSo8nRXCPRjjE6dg="

API_HOST_URL = "http://127.0.0.1:8000"
UI_HOST_URL = "http://127.0.0.1:3000"
BACKEND_CORS_ORIGINS = [UI_HOST_URL]

OPENSEARCH_HOST = "localhost"
# OPENSEARCH_HOST = "opensearch-node1"
OPENSEARCH_PORT = "9200"
OPENSEARCH_USERNAME = "admin"
OPENSEARCH_PASSWORD = "admin"

USERNAME_AND_PASSWORD_ENABLED = True
ADMIN_EMAIL = "email@something.com"
ADMIN_PASSWORD = "admin"

GITHUB_OAUTH_ENABLED = False
GITHUB_OAUTH_CLIENT_ID = None
GITHUB_OAUTH_SECRET = None

GOOGLE_OAUTH_ENABLED = False
GOOGLE_OAUTH_CLIENT_ID = None
GOOGLE_OAUTH_SECRET = None

MICROSOFT_OAUTH_ENABLED = False
MICROSOFT_OAUTH_CLIENT_ID = None
MICROSOFT_OAUTH_SECRET = None
MICROSOFT_OAUTH_TENANT = None  # defaults to "common" when not set

OKTA_OAUTH_ENABLED = False
OKTA_OAUTH_CLIENT_ID = None
OKTA_OAUTH_SECRET = None
OKTA_OAUTH_BASE_URL = None



