env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  'react/jsx-props-no-spreading': 0,
  'no-nested-ternary': 0,
}
