name: Deployment Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish-docker-images:
    uses: ./.github/workflows/build-and-publish-docker-images.yml