name: Deployment Workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - frontend/**
      - backend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - frontend/**
      - backend/**

jobs:
  publish-docker-images:
    uses: ./.github/workflows/publish-docker-images.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}