name: github-repo-stats

on:
  pull_request:
    branches:
      - main

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
