name: Deploy Docker Images

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: FranzDiebold/github-env-vars-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/swiple-api
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#        name: Build and push PR Docker Image
#        uses: docker/build-push-action@v3
#        if: ${{ github.event_name == 'pull_request' }}
#        with:
#          context: ./backend/
#          file: ./backend/Dockerfile
#          push: true
#          tags: "swiple/swiple-api:pr-${{ env.CI_PR_NUMBER }}"
#      -
#        name: Build and push main Docker Image
#        uses: docker/build-push-action@v3
#        if: ${{ github.ref == 'refs/heads/main' }}
#        with:
#          context: ./backend/
#          file: ./backend/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/swiple-api:latest"