name: Deploy Docker Images

on: [pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: FranzDiebold/github-env-vars-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push PR Docker Image
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == "pull_request" }}
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: "swiple/swiple-api:pr-${{ env.CI_PR_NUMBER }}"