AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DomainName:
    Type: String
    Default: swiple.io
Resources:
  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
        - !Sub "test.${DomainName}"
        - !Sub "www.test.${DomainName}"
Outputs:
  CertificateARN:
    Value: !Ref Certificate
    Export:
      Name: SwipleDomainCertificateArn